name: metrics-backend

services:
  # app:
  #   image: ...
  postgresdb:
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metricsdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4:8.14.0
  #   ports:
  #     - '5050:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dev1@metrics.com
  #     PGADMIN_DEFAULT_PASSWORD: abc123
  #   depends_on:
  #     - postgresdb
volumes:
  postgres_data:
  # pgadmin_data:
