DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'metrics') THEN
        CREATE SCHEMA metrics;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS metrics.__ef_migrations_history (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'metrics') THEN
        CREATE SCHEMA metrics;
    END IF;
END $EF$;

CREATE TABLE metrics.asp_net_roles (
    id text NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT "PK_asp_net_roles" PRIMARY KEY (id)
);

CREATE TABLE metrics.asp_net_users (
    id text NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT "PK_asp_net_users" PRIMARY KEY (id)
);

CREATE TABLE metrics.departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    department_code uuid NOT NULL,
    department_name varchar(500) NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE metrics.kpi_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    period_name varchar(20) NOT NULL,
    submission_start_date timestamp with time zone NOT NULL,
    submission_end_date timestamp with time zone NOT NULL,
    CONSTRAINT pk_kpi_periods PRIMARY KEY (id)
);

CREATE TABLE metrics.application_roles (
    id text NOT NULL,
    CONSTRAINT "PK_application_roles" PRIMARY KEY (id),
    CONSTRAINT fk_application_roles_asp_net_roles_id FOREIGN KEY (id) REFERENCES metrics.asp_net_roles (id) ON DELETE CASCADE
);

CREATE TABLE metrics.asp_net_role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES metrics.asp_net_roles (id) ON DELETE CASCADE
);

CREATE TABLE metrics.application_users (
    id text NOT NULL,
    CONSTRAINT "PK_application_users" PRIMARY KEY (id),
    CONSTRAINT fk_application_users_asp_net_users_id FOREIGN KEY (id) REFERENCES metrics.asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE metrics.asp_net_user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES metrics.asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE metrics.asp_net_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES metrics.asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE metrics.asp_net_user_roles (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES metrics.asp_net_roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES metrics.asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE metrics.asp_net_user_tokens (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES metrics.asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE metrics.employees (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    employee_code varchar(100) NOT NULL,
    full_name varchar(200) NOT NULL,
    address text,
    phone_number varchar(200),
    department_id bigint NOT NULL,
    application_user_id text NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT fk_employees_application_users_application_user_id FOREIGN KEY (application_user_id) REFERENCES metrics.application_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_employees_departments_department_id FOREIGN KEY (department_id) REFERENCES metrics.departments (id) ON DELETE RESTRICT
);

CREATE TABLE metrics.kpi_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    submission_time timestamp with time zone NOT NULL,
    kpi_score numeric(4,2) NOT NULL,
    comments text,
    submission_date date GENERATED ALWAYS AS (DATE(submission_time AT TIME ZONE 'UTC')) STORED NOT NULL,
    kpi_period_id bigint NOT NULL,
    department_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT pk_kpi_submissions PRIMARY KEY (id),
    CONSTRAINT fk_kpi_submissions_departments_department_id FOREIGN KEY (department_id) REFERENCES metrics.departments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_kpi_submissions_employees_employee_id FOREIGN KEY (employee_id) REFERENCES metrics.employees (id) ON DELETE RESTRICT,
    CONSTRAINT fk_kpi_submissions_kpi_periods_kpi_period_id FOREIGN KEY (kpi_period_id) REFERENCES metrics.kpi_periods (id) ON DELETE RESTRICT
);

CREATE INDEX ix_asp_net_role_claims_role_id ON metrics.asp_net_role_claims (role_id);

CREATE UNIQUE INDEX "RoleNameIndex" ON metrics.asp_net_roles (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON metrics.asp_net_user_claims (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON metrics.asp_net_user_logins (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON metrics.asp_net_user_roles (role_id);

CREATE INDEX "EmailIndex" ON metrics.asp_net_users (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON metrics.asp_net_users (normalized_user_name);

CREATE UNIQUE INDEX ix_departments_department_code ON metrics.departments (department_code);

CREATE UNIQUE INDEX ix_departments_department_name ON metrics.departments (department_name);

CREATE UNIQUE INDEX ix_employees_application_user_id ON metrics.employees (application_user_id);

CREATE INDEX ix_employees_department_id ON metrics.employees (department_id);

CREATE UNIQUE INDEX ix_employees_employee_code ON metrics.employees (employee_code);

CREATE UNIQUE INDEX ix_kpi_periods_period_name ON metrics.kpi_periods (period_name);

CREATE INDEX ix_kpi_submissions_department_id ON metrics.kpi_submissions (department_id);

CREATE INDEX ix_kpi_submissions_employee_id ON metrics.kpi_submissions (employee_id);

CREATE INDEX ix_kpi_submissions_kpi_period_id ON metrics.kpi_submissions (kpi_period_id);

CREATE UNIQUE INDEX ix_kpi_submissions_submission_date ON metrics.kpi_submissions (submission_date);

INSERT INTO metrics.__ef_migrations_history (migration_id, product_version)
VALUES ('20250308152412_InitDb', '9.0.2');

DROP INDEX metrics.ix_kpi_submissions_kpi_period_id;

DROP INDEX metrics.ix_kpi_submissions_submission_date;

CREATE UNIQUE INDEX ix_kpi_submissions_kpi_period_id_department_id_employee_id ON metrics.kpi_submissions (kpi_period_id, department_id, employee_id);

INSERT INTO metrics.__ef_migrations_history (migration_id, product_version)
VALUES ('20250324045555_Change_SubmissionDate_To_NotUnique', '9.0.2');

COMMIT;

